id: P55B7E7AB
initial_creation_type: input
source_metadata:
  title: Ten Royal Sūtras
  language: de
  description: 'A collection related to the ten royal sūtras or ten sūtras of the
    king (rgyal po''i mdo bcu), which are said to have been translated upon the advice
    of Padmasambhava for Emperor Tri Songdetsen''s daily recitation:'
  volume:
    0d9a604483714b64935ad20cc1ac58c5:
      title: Outline of the Ten Royal Sūtras
      parent: Outlines
    9a97ad88e51e4b76b29049a49bcc04d5:
      title: The Bodhisattva’s Confession of Downfalls (Nyingma Version)
      parent: Sūtras
    d7f4ea353f374cf48c960686735564e2:
      title: The Dhāraṇī of Stream of Wealth (Vasudhārā)
      parent: Sūtras
    efb2457abae24f3fbadccec088fb04f3:
      title: The Heart of the Transcendent Perfection of Wisdom
      parent: Sūtras
    69792bb382e34ec283a2d6f7cf85caa3:
      title: 'The King of Aspiration Prayers: Samantabhadra''s “Aspiration to Good
        Actions” (Zangchö Mönlam)'
      parent: Sūtras
    05620f82ae084a919a31ee0bf6344015:
      title: The Noble Dhāraṇī of The Supreme Accomplishment of Sitātapatrā Born from
        the Tathāgata’s Uṣṇīṣa, the Great Invincible Dispeller
      parent: Sūtras
    12ce0a1b8f464609815948062b1d5ca3:
      title: The Noble Incantation entitled ‘The Rituals for the Blue-Clad Vajrapāṇi’
      parent: Sūtras
    e3795ddd71ea46589eafa396295b2e4d:
      title: The Noble Mahāyāna Sūtra entitled The Wisdom of the Hour of Death
      parent: Sūtras
    b335bc2926cc44579314c08dadaf8485:
      title: The Perfection of Wisdom, Mother of All Tathāgatas, ‘In One Syllable’
      parent: Sūtras
    90b62f2cb516420ba7ba5a1352be409b:
      title: The Sūtra of Boundless Life and Wisdom
      parent: Sūtras
    f7eca21c13ad462597980114fa8a0b8b:
      title: Vajravidāraṇa Dhāraṇī (Nyingma Version)
      parent: Sūtras
created_at: '2022-03-01T06:06:38.011726'
last_modified_at: '2022-03-01T06:06:38.011729'
